org: ashutosh619

app: aws-serverless

service: aws-infra

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  httpApi:
    id: 0cdqat35hg

  environment:
    MY_VAL: "test-1"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get

